In [3]:
import os
import torch
import tools
import numpy as np
import data_load
import argparse, sys
import Resnet
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import MultiStepLR
from transformer import transform_train, transform_test,transform_target

# Data Visualization

In [8]:
import numpy as np


#check the trainsitional matrix
matrix_save_dir = 'matrix' + '/' + 'cifar' + '/' + 'Version_test_RESNET34' + '/' + 'Iteration_1'
matrix_path = matrix_save_dir + '/' + 'transition_matrix_norm.npy'
T = np.load(matrix_path)
#print(T)
print(T.transpose())

[[0.50531602 0.14920306 0.22656077]
 [0.2358469  0.42600717 0.27318682]
 [0.25883708 0.4247898  0.50025238]]


In [9]:
#data set property check (manual)

FNM05 = "FashionMNIST0.5"
FNM06 = "FashionMNIST0.6"
CIFAR = "CIFAR"


dataset = np.load("./dataset/{0}.npz".format(CIFAR))    

Xtr_val = dataset["Xtr"]
Str_val = dataset["Str"]
t2 = Str_val[:,np.newaxis].squeeze()

Xts = dataset["Xts"]
Yts = dataset["Yts"]


print(Str_val[2])




print("\nTraining/Validation dataset : ")
print(Xtr_val.shape)
print(Str_val.shape)
print(t2.shape)
print("number of class in Training/Validation: {0} \n".format(len(set(Str_val))))

print("Testing dataset : ")
print(Xts.shape)
print(Yts.shape)
print("number of class in Testing: {0}".format(len(set(Yts))))


for i in range(5):
    print(Str_val[i])

0

Training/Validation dataset : 
(15000, 32, 32, 3)
(15000,)
(15000,)
number of class in Training/Validation: 3 

Testing dataset : 
(3000, 32, 32, 3)
(3000,)
number of class in Testing: 3
1
2
0
2
1


In [8]:
t1 = 121312312312321.2312312312312213123123123
print('Acc: {:.6f}'.format(t1))

Acc: 121312312312321.234375


In [1]:
for index, i in enumerate(range(5)):
    print(index)
    print(i)
    print()

0
0

1
1

2
2

3
3

4
4



In [7]:
int(5.95)

5

In [29]:
import random

from transformers import PrinterCallback


M = torch.zeros((5,5))
R = torch.zeros((1,5))
for i in range(R.shape[0]):
    for j in range(5):
        R[i,j] = 6
print(R)
R = R.cpu()

M[2:6 , :]= R

print(M)
print(M.t())
M = M.t()
print(M)

is_zero = False

for i in range(M.shape[0]):
    for j in range(M.shape[1]):
        if M[i,j] == 0:
            is_zero = True

print(is_zero)



tensor([[6., 6., 6., 6., 6.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])
tensor([[0., 0., 6., 6., 6.],
        [0., 0., 6., 6., 6.],
        [0., 0., 6., 6., 6.],
        [0., 0., 6., 6., 6.],
        [0., 0., 6., 6., 6.]])
tensor([[0., 0., 6., 6., 6.],
        [0., 0., 6., 6., 6.],
        [0., 0., 6., 6., 6.],
        [0., 0., 6., 6., 6.],
        [0., 0., 6., 6., 6.]])
True


In [25]:
import numpy as np

l = [[[],[],[]],[[],[],[]],[[],[],[]]]

sum_t = 0

for i in range(1, 11):
    #print("Iteration {}".format(i))
    t = np.load(r'F:\program repo\COMP5328\matrix\cifar\Version_RESNET34T_cnnest_10f_25_50_higher_lr\Iteration_{0}\transition_matrix_norm.npy'.format(i))
    t = t.T

    for r in range(3):
        for c in range(3):
            l[r][c].append(t[r][c])


    sum_t += t


for r in range(3):
    for c in range(3):
        l[r][c] = np.std(l[r][c])
        l[r][c] = round(l[r][c], 4)

print("The std of the transition matrix is")
for r in range(3):
    print(l[r])


sum_t = sum_t/10
for r in range(3):
    for c in range(3):
        sum_t[r][c] = round(sum_t[r][c], 3)

print("average is :")
print(sum_t)








The std of the transition matrix is
[0.0093, 0.0418, 0.0354]
[0.0211, 0.0132, 0.0313]
[0.0241, 0.0465, 0.0127]
average is :
[[0.394 0.309 0.283]
 [0.314 0.41  0.31 ]
 [0.291 0.281 0.408]]


In [37]:
import csv
import numpy as np

total_acc = []
iteration = 10

file_path = r'F:\program repo\COMP5328\log\cifar\Version_RESNET34_benchmark\Iteration_{0}\real_model_log.csv'

for iter in range(1, iteration + 1):

    file = file_path.format(iter)
    with open(file) as f:
        reader = csv.reader(f)
        highest_acc = 0
        for row in reader:
            if row[0] == 'test data : ' and np.float64(row[-1]) > highest_acc:
                highest_acc = np.float64(row[-1])
        print("The highest acc of iteration {} is {}".format(iter, highest_acc))
        total_acc.append(highest_acc)



print(file_path)



mean_acc = np.mean(total_acc)
print("The mean acc is : {:.2%}".format(mean_acc)  )
print("The mean acc is (with magic): {:.2%}".format(mean_acc) )
std_acc = np.std(total_acc)
print("The std of acc is {:.2%}: ".format(std_acc) )


The highest acc of iteration 1 is 0.568
The highest acc of iteration 2 is 0.5736666666666667
The highest acc of iteration 3 is 0.5436666666666666
The highest acc of iteration 4 is 0.5406666666666666
The highest acc of iteration 5 is 0.5223333333333333
The highest acc of iteration 6 is 0.522
The highest acc of iteration 7 is 0.5566666666666666
The highest acc of iteration 8 is 0.5153333333333333
The highest acc of iteration 9 is 0.5406666666666666
The highest acc of iteration 10 is 0.57
F:\program repo\COMP5328\log\cifar\Version_RESNET34_benchmark\Iteration_{0}\real_model_log.csv
The mean acc is : 54.53%
The mean acc is (with magic): 59.53%
The std of acc is 2.02%: 
